# Generated by Django 5.1.4 on 2024-12-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
