# Generated by Django 5.1.4 on 2024-12-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_note_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='data',
            field=models.DateField(auto_now_add=True, default='default title', verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
