# Generated by Django 5.1.4 on 2024-12-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_note_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='data',
        ),
    ]
